# Generated by Django 4.1.1 on 2023-03-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0003_rename_reactants_operation_arguments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.CharField(max_length=250)),
                ('video_streams', models.JSONField()),
            ],
        ),
    ]
