version: '3.8'
services:
  backend:
    container_name: osl_backend
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  
  redis:
    image: "redis:alpine"
    container_name: osl_redis
    restart: always
    ports:
      - "6380:6379"
  
  mqttservice:
     container_name: osl_mqtt
     build:
      context: .
     command: 'python -u mqttConsumer.py'
     depends_on:
      - db
   
    

  db:
    image: postgres
    container_name: osl_db
    restart: always
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/postgres
    ports:
      - 5432:5432

